name: cradle
version: 0.0.0.0
synopsis: A simpler process library
description: |
  This library provides an intuitive, simple, and composable interface for
  running system processes. Think of it as a higher-level `process`.
author: garnix team <dev@garnix.io>
maintainer: garnix team <dev@garnix.io>
github: garnix-io/cradle
category: System

dependencies:
  - base >= 4.5 && < 5
  - bytestring
  - process
  - string-conversions
  - text
  - unix

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -threaded

c-sources:
  cbits/cradle.c

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -fdefer-typed-holes
    dependencies:
      - directory
      - filepath
      - hspec
      - hspec-discover
      - interpolate
      - mockery
      - silently
      - transformers
      - unix
  readme:
    main: README.lhs
    dependencies:
      - cradle
      - markdown-unlit
    ghc-options:
      - -pgmL markdown-unlit

library:
  source-dirs:
    - src
