name: cradle
version: 0.0.0.0

dependencies:
  - base
  - bytestring
  - process
  - text

ghc-options:
  - -Wall
  - -Wno-name-shadowing
  - -threaded

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -fdefer-typed-holes
    dependencies:
      - directory
      - hspec
      - hspec-discover
      - mockery
      - silently
      - string-conversions
      - transformers

library:
  source-dirs:
    - src
  exposed-modules:
    - Cradle
